# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ironveil RP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ironveilrp/launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gQ8QpJqmK9"

[ejs.settings]
sourceGithubLink = "https://github.com/ironveilrp/launcher"
supportLink = "https://github.com/ironveilrp/launcher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Ironveil RP"
welcomeDescription = "An unforgettable experience."
welcomeDescCTA = "Click below to log into your Minecraft account"
