# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ironveil RP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ironveilrp/launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gQ8QpJqmK9"

[ejs.settings]
sourceGithubLink = "https://github.com/ironveilrp/launcher"
supportLink = "https://github.com/ironveilrp/launcher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Ironveil RP"
welcomeDescription = "I met a traveller from an antique land,<br>
Who said—“Two vast and trunkless legs of stone<br>
Stand in the desert. . . . Near them, on the sand,<br>
Half sunk a shattered visage lies, whose frown,<br>
And wrinkled lip, and sneer of cold command,<br>
Tell that its sculptor well those passions read<br>
Which yet survive, stamped on these lifeless things,<br>
The hand that mocked them, and the heart that fed;<br>
And on the pedestal, these words appear:<br>
My name is Ozymandias, King of Kings;<br>
Look on my Works, ye Mighty, and despair!<br>
Nothing beside remains. Round the decay<br>
Of that colossal Wreck, boundless and bare<br>
The lone and level sands stretch far away.”"
welcomeDescCTA = "Click below to log into your Minecraft account"
